name: train_delivery_app
description: Smart Train Food Delivery System — Passenger + Staff
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  # Add when wiring these next:
  # multicast_dns: ^0.3.2+7   # for ESP32 mDNS auto-discovery

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#08080C"
    theme_color: "#3B82F6"
  windows:
    generate: false
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/siren.mp3
    - assets/icon/app_icon.png